insert into books(title, author, description, image, ISBN10, ISBN13) values ('IN THE YEAR OF LONG DIVISION', 'Dawn. Raffel', '', 'http://g-ecx.images-amazon.com/images/G/01/nav2/dp/no-image-no-ciu._V192545765_AA300_.gif','','');


insert into books(title, author, description, image, ISBN10, ISBN13) values ('Further Adventures in the Restless Universe: Stories', 'Dawn Raffel', 'short stories', 'http://ecx.images-amazon.com/images/I/410cG%2BiokCL._BO2,204,203,200_PIsitb-sticker-arrow-click,TopRight,35,-76_AA300_SH20_OU01_.jpg', '0976717794', '978-0976717799'

insert into books(title, author, description, image, ISBN10, ISBN13) values ('The Couch', 'Benjamin Parzybok', 'Thom is a computer geek whose hacking of a certain Washington-based software giant has won him a little fame but few job prospects. Erik is a smalltime con man, a fast-talker who is never quite quick enough on his feet. Their roommate, Tree, is a confused clairvoyant whose dreams and prophecies may not be completely off base. After a freak accident fl oods their apartment, the three are evicted—but they have to take their couch with them. The real problem? The couch—huge and orange—won’t let them put it down. Soon the three roommates are on a cross-country trek along back roads, byways, and rail lines, heading far out of Portland and deep into one very weird corner of the American dream.Benjamin Parzybok is the creator of Gumball Poetry, a journal published through gumball machines, and the Black Magic Insurance Agency, a city-wide mystery/treasure hunt. He has worked as a congressional page, a ghostwriter for the governor of Washington, a web developer, a Taiwanese factory technical writer, an asbestos removal janitor, and a potato sorter. He lives in Portland, Oregon, with the writer Laura Moulton and their two children.','http://ecx.images-amazon.com/images/I/51FdVM%2BERAL._BO2,204,203,200_PIsitb-sticker-arrow-click,TopRight,35,-76_AA300_SH20_OU01_.jpg', '1931520542', '978-1931520546'


insert into books(title, author, description, image, ISBN10, ISBN13) values ('Pigeon English', 'Stephen Kelman', 'Lying in front of Harrison Opoku is a body, the body of one of his classmates, a boy known for his crazy basketball skills, who seems to have been murdered for his dinner.Armed with a pair of camouflage binoculars and detective techniques absorbed from television shows like CSI, Harri and his best friend, Dean, plot to bring the perpetrator to justice. They gather evidence—fingerprints lifted from windows with tape, a wallet stained with blood—and lay traps to flush out the murderer. But nothing can prepare them for what happens when a criminal feels you closing in on him.Recently emigrated from Ghana with his sister and mother to London’s enormous housing projects, Harri is pure curiosity and ebullience—obsessed with gummy candy, a friend to the pigeon who visits his balcony, quite possibly the fastest runner in his school, and clearly also fast on the trail of a murderer.Told in Harri''s infectious voice and multicultural slang, Pigeon English follows in the tradition of our great novels of friendship and adventure, as Harri finds wonder, mystery, and danger in his new, ever-expanding world.','http://g-ecx.images-amazon.com/images/G/01/nav2/dp/no-image-no-ciu._V192545765_AA300_.gif', '0547500602', ''

insert into books(title, author, description, image, ISBN10, ISBN13) values ('The Book Of The Dead', 'Sir E. A. Wallis Budge', 'Anthology on Classic Literature','http://ecx.images-amazon.com/images/I/51D2vz76C3L._BO2,204,203,200_PIsitb-sticker-arrow-click,TopRight,35,-76_AA300_SH20_OU01_.jpg', '1463688822', '978-1463688820'

insert into books(title, author, description, image, ISBN10, ISBN13) values ('The Book Of The Dead', 'Douglas Preston and Lincoln Child', 'Mystery & Suspense Thriller','http://ecx.images-amazon.com/images/I/51UukIGZX7L._BO2,204,203,200_PIsitb-sticker-arrow-click,TopRight,35,-76_AA300_SH20_OU01_.jp', '0446618500', '978-0446618502'


